[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart-pytorch-lightning"
version = "0.1.0"
description = "Federated Learning Quickstart with Flower and PyTorch Lightning"
authors = ["The Flower Authors <hello@flower.ai>"]

[tool.poetry.dependencies]
python = "^3.8"
flwr = ">=1.0,<2.0"
# flwr = { path = "../../", develop = true }  # Development
flwr-datasets = { extras = ["vision"], version = ">=0.0.2,<1.0.0" }
pytorch-lightning = "1.6.0"
torchvision = "0.14.1"
