[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "sklearn-mnist"
version = "0.1.0"
description = "Federated learning with scikit-learn and Flower"
authors = [
    "The Flower Authors <hello@flower.ai>",
    "Kaushik Amar Das <kaushik.das@iiitg.ac.in>",
]

[tool.poetry.dependencies]
python = "^3.8"
flwr = ">=1.0,<2.0"
# flwr = { path = "../../", develop = true }  # Development
flwr-datasets = { extras = ["vision"], version = ">=0.0.2,<1.0.0" }
scikit-learn = "^1.1.1"
