[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fl-tabular"
version = "0.1.0"
description = "Adult Census Income Tabular Dataset and Federated Learning in Flower"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
dependencies = [
    "flwr[simulation]>=1.9.0,<2.0",
    "flwr-datasets>=0.1.0,<1.0.0",
    "torch==2.1.1",
    "scikit-learn==1.5.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
