name: Publish `flwr` release on PyPI

on:
  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ARTIFACT_BUCKET: artifact.flower.ai

jobs:
  publish:
    if: ${{ github.repository == 'adap/flower' }}
    name: Publish release
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Bootstrap
      uses: ./.github/actions/bootstrap

    - name: Get artifacts and publish
      env:
        GITHUB_REF: ${{ github.ref }}
      run: |
        TAG_NAME=$(echo "${GITHUB_REF_NAME}" | cut -c2-)

        wheel_name="flwr-${TAG_NAME}-py3-none-any.whl"
        tar_name="flwr-${TAG_NAME}.tar.gz"

        wheel_url="https://${{ env.ARTIFACT_BUCKET }}/py/release/v${TAG_NAME}/${wheel_name}"
        tar_url="https://${{ env.ARTIFACT_BUCKET }}/py/release/v${TAG_NAME}/${tar_name}"

        mkdir -p dist

        curl $wheel_url --output dist/$wheel_name
        curl $tar_url --output dist/$tar_name

        python -m poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN_RELEASE_FLWR }}
