name: PR update

on:
  push:
    branches:
      - 'main'
jobs:
  autoupdate:
    runs-on: ubuntu-22.04
    steps:
      - name: Automatically update mergeable PRs
        uses: adRise/update-pr-branch@3576c22e28fb6f665417bfe3a83f9da7ca5363e2 # v0.9.1
        with:
          token: ${{ secrets.FLWRMACHINE_TOKEN }}
          base: 'main'
          required_approval_count: 1
          require_passed_checks: true
          sort: 'created'
          direction: 'desc'
